// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: test32

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t *ui_mainScreen;
lv_obj_t *ui_arcTemp;
lv_obj_t *ui_lbTemp;
lv_obj_t *ui_lbTempSecondary;
lv_obj_t *ui_btAcPower;
lv_obj_t *ui_lbConstAcPower;
lv_obj_t *ui_lbConstAcMinus;
lv_obj_t *ui_lbConstAcPlus;
lv_obj_t *ui_btAcPlus;
lv_obj_t *ui_btAcMinus;
lv_obj_t *ui_btAcSet;
lv_obj_t *ui_btColorAuto;
lv_obj_t *ui_lbConstColorAuto;
void ui_event_btConfig( lv_event_t * e);
lv_obj_t *ui_btConfig;
lv_obj_t *ui_lbConstConfig;
lv_obj_t *ui_Bar1;
lv_obj_t *ui_lbInfo;
void ui_event_btLock( lv_event_t * e);
lv_obj_t *ui_btLock;
lv_obj_t *ui_pnConfig;
lv_obj_t *ui_lbConstDeviceName;
lv_obj_t *ui_lbConstLed;
lv_obj_t *ui_swLed;
lv_obj_t *ui_lbConstIP;
lv_obj_t *ui_lbIP;
lv_obj_t *ui_lbConstBoot;
lv_obj_t *ui_lbBoot;
void ui_event_btBack( lv_event_t * e);
lv_obj_t *ui_btBack;
lv_obj_t *ui_lbConstbtBack;
lv_obj_t *ui_btReset;
lv_obj_t *ui_lbConstbtReset;
lv_obj_t *ui_arcRam;
lv_obj_t *ui_lbRamValue;
lv_obj_t *ui_lbConstRam;
lv_obj_t *ui_arcFS;
lv_obj_t *ui_lbFSValue;
lv_obj_t *ui_lbConstFS;


// SCREEN: ui_lockScreen
void ui_lockScreen_screen_init(void);
lv_obj_t *ui_lockScreen;
void ui_event_imgLogo( lv_event_t * e);
lv_obj_t *ui_imgLogo;
lv_obj_t *ui_lbTime;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_1060162954[2] = {&ui_img_1529088296, &ui_img_634369039};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_btConfig( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_pnConfig, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_btLock( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_lockScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_lockScreen_screen_init);
}
}
void ui_event_btBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_pnConfig, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_imgLogo( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_mainScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_mainScreen_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_mainScreen_screen_init();
ui_lockScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_mainScreen);
}
