// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: test32

#include "../ui.h"

void ui_lockScreen_screen_init(void)
{
ui_lockScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_lockScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_lockScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lockScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imgLogo = lv_img_create(ui_lockScreen);
lv_img_set_src(ui_imgLogo, &ui_img_1529088296);
lv_obj_set_width( ui_imgLogo, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_imgLogo, LV_SIZE_CONTENT);   /// 270
lv_obj_set_x( ui_imgLogo, 0 );
lv_obj_set_y( ui_imgLogo, -20 );
lv_obj_set_align( ui_imgLogo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgLogo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgLogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lbTime = lv_label_create(ui_lockScreen);
lv_obj_set_width( ui_lbTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbTime, 0 );
lv_obj_set_y( ui_lbTime, 130 );
lv_obj_set_align( ui_lbTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbTime,"HH:MM");
lv_obj_set_style_text_font(ui_lbTime, &ui_font_FontMono2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_imgLogo, ui_event_imgLogo, LV_EVENT_ALL, NULL);

}
