// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: test32

#include "../ui.h"

void ui_mainScreen_screen_init(void)
{
ui_mainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_mainScreen, LV_SCROLLBAR_MODE_ON);

ui_arcTemp = lv_arc_create(ui_mainScreen);
lv_obj_set_width( ui_arcTemp, 150);
lv_obj_set_height( ui_arcTemp, 150);
lv_obj_set_x( ui_arcTemp, 0 );
lv_obj_set_y( ui_arcTemp, -65 );
lv_obj_set_align( ui_arcTemp, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_arcTemp, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_bg_color(ui_arcTemp, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_arcTemp, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_lbTemp = lv_label_create(ui_arcTemp);
lv_obj_set_width( ui_lbTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lbTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbTemp,"25.5");
lv_obj_set_style_text_font(ui_lbTemp, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbTempSecondary = lv_label_create(ui_arcTemp);
lv_obj_set_width( ui_lbTempSecondary, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbTempSecondary, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbTempSecondary, 0 );
lv_obj_set_y( ui_lbTempSecondary, 51 );
lv_obj_set_align( ui_lbTempSecondary, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbTempSecondary,"25.2 C");
lv_obj_set_style_text_font(ui_lbTempSecondary, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btAcPower = lv_btn_create(ui_mainScreen);
lv_obj_set_width( ui_btAcPower, 115);
lv_obj_set_height( ui_btAcPower, 50);
lv_obj_set_x( ui_btAcPower, 2 );
lv_obj_set_y( ui_btAcPower, 41 );
lv_obj_set_align( ui_btAcPower, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_btAcPower, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btAcPower, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lbConstAcPower = lv_label_create(ui_btAcPower);
lv_obj_set_width( ui_lbConstAcPower, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbConstAcPower, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lbConstAcPower, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbConstAcPower,"Power");
lv_obj_set_style_text_font(ui_lbConstAcPower, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbConstAcMinus = lv_label_create(ui_mainScreen);
lv_obj_set_width( ui_lbConstAcMinus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbConstAcMinus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbConstAcMinus, -102 );
lv_obj_set_y( ui_lbConstAcMinus, -75 );
lv_obj_set_align( ui_lbConstAcMinus, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbConstAcMinus,"-");
lv_obj_set_style_text_font(ui_lbConstAcMinus, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbConstAcPlus = lv_label_create(ui_mainScreen);
lv_obj_set_width( ui_lbConstAcPlus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbConstAcPlus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbConstAcPlus, 102 );
lv_obj_set_y( ui_lbConstAcPlus, -70 );
lv_obj_set_align( ui_lbConstAcPlus, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbConstAcPlus,"+");
lv_obj_set_style_text_font(ui_lbConstAcPlus, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btAcPlus = lv_btn_create(ui_mainScreen);
lv_obj_set_width( ui_btAcPlus, 70);
lv_obj_set_height( ui_btAcPlus, 130);
lv_obj_set_x( ui_btAcPlus, 0 );
lv_obj_set_y( ui_btAcPlus, 35 );
lv_obj_set_align( ui_btAcPlus, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_btAcPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btAcPlus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btAcPlus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btAcPlus, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btAcMinus = lv_btn_create(ui_mainScreen);
lv_obj_set_width( ui_btAcMinus, 70);
lv_obj_set_height( ui_btAcMinus, 130);
lv_obj_set_x( ui_btAcMinus, 0 );
lv_obj_set_y( ui_btAcMinus, 35 );
lv_obj_add_flag( ui_btAcMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btAcMinus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btAcMinus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btAcMinus, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btAcSet = lv_btn_create(ui_mainScreen);
lv_obj_set_width( ui_btAcSet, 100);
lv_obj_set_height( ui_btAcSet, 130);
lv_obj_set_x( ui_btAcSet, 0 );
lv_obj_set_y( ui_btAcSet, 35 );
lv_obj_set_align( ui_btAcSet, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_btAcSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btAcSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btAcSet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btAcSet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btColorAuto = lv_btn_create(ui_mainScreen);
lv_obj_set_width( ui_btColorAuto, 115);
lv_obj_set_height( ui_btColorAuto, 50);
lv_obj_set_x( ui_btColorAuto, 2 );
lv_obj_set_y( ui_btColorAuto, 41 );
lv_obj_set_align( ui_btColorAuto, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_btColorAuto, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btColorAuto, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lbConstColorAuto = lv_label_create(ui_btColorAuto);
lv_obj_set_width( ui_lbConstColorAuto, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbConstColorAuto, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lbConstColorAuto, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbConstColorAuto,"Auto");
lv_obj_set_style_text_font(ui_lbConstColorAuto, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btConfig = lv_btn_create(ui_mainScreen);
lv_obj_set_width( ui_btConfig, 115);
lv_obj_set_height( ui_btConfig, 50);
lv_obj_set_x( ui_btConfig, -2 );
lv_obj_set_y( ui_btConfig, 116 );
lv_obj_set_align( ui_btConfig, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_btConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btConfig, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lbConstConfig = lv_label_create(ui_btConfig);
lv_obj_set_width( ui_lbConstConfig, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbConstConfig, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lbConstConfig, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbConstConfig,"Config");
lv_obj_set_style_text_font(ui_lbConstConfig, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar1 = lv_bar_create(ui_mainScreen);
lv_bar_set_value(ui_Bar1,100,LV_ANIM_OFF);
lv_obj_set_height( ui_Bar1, 5);
lv_obj_set_width( ui_Bar1, lv_pct(46));
lv_obj_set_y( ui_Bar1, 12 );
lv_obj_set_x( ui_Bar1, lv_pct(27) );
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );

lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_lbInfo = lv_label_create(ui_mainScreen);
lv_obj_set_width( ui_lbInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbInfo, 87 );
lv_obj_set_y( ui_lbInfo, -143 );
lv_obj_set_align( ui_lbInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbInfo,"MQTT");
lv_obj_add_flag( ui_lbInfo, LV_OBJ_FLAG_CLICKABLE );   /// Flags

ui_btLock = lv_btn_create(ui_mainScreen);
lv_obj_set_width( ui_btLock, 110);
lv_obj_set_height( ui_btLock, 55);
lv_obj_set_x( ui_btLock, 125 );
lv_obj_set_y( ui_btLock, 0 );
lv_obj_add_flag( ui_btLock, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btLock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btLock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btLock, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pnConfig = lv_obj_create(ui_mainScreen);
lv_obj_set_width( ui_pnConfig, lv_pct(105));
lv_obj_set_height( ui_pnConfig, lv_pct(105));
lv_obj_set_align( ui_pnConfig, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_pnConfig, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_pnConfig, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_pnConfig, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pnConfig, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbConstDeviceName = lv_label_create(ui_pnConfig);
lv_obj_set_width( ui_lbConstDeviceName, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbConstDeviceName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lbConstDeviceName, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_lbConstDeviceName,"Moriarty");
lv_obj_set_style_text_font(ui_lbConstDeviceName, &ui_font_FontMono2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbConstLed = lv_label_create(ui_pnConfig);
lv_obj_set_width( ui_lbConstLed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbConstLed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbConstLed, -140 );
lv_obj_set_y( ui_lbConstLed, 50 );
lv_obj_set_align( ui_lbConstLed, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_lbConstLed,"LED :");
lv_obj_set_style_text_font(ui_lbConstLed, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_swLed = lv_switch_create(ui_pnConfig);
lv_obj_set_width( ui_swLed, 60);
lv_obj_set_height( ui_swLed, 30);
lv_obj_set_x( ui_swLed, 120 );
lv_obj_set_y( ui_swLed, 49 );


ui_lbConstIP = lv_label_create(ui_pnConfig);
lv_obj_set_width( ui_lbConstIP, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbConstIP, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbConstIP, -140 );
lv_obj_set_y( ui_lbConstIP, 90 );
lv_obj_set_align( ui_lbConstIP, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_lbConstIP,"IP:");
lv_obj_set_style_text_font(ui_lbConstIP, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbIP = lv_label_create(ui_pnConfig);
lv_obj_set_width( ui_lbIP, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbIP, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbIP, 100 );
lv_obj_set_y( ui_lbIP, 90 );
lv_label_set_text(ui_lbIP,"10.10.10.10");
lv_obj_set_style_text_font(ui_lbIP, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbConstBoot = lv_label_create(ui_pnConfig);
lv_obj_set_width( ui_lbConstBoot, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbConstBoot, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbConstBoot, -140 );
lv_obj_set_y( ui_lbConstBoot, 130 );
lv_obj_set_align( ui_lbConstBoot, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_lbConstBoot,"Boot:");
lv_obj_set_style_text_font(ui_lbConstBoot, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbBoot = lv_label_create(ui_pnConfig);
lv_obj_set_width( ui_lbBoot, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbBoot, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbBoot, 100 );
lv_obj_set_y( ui_lbBoot, 130 );
lv_label_set_text(ui_lbBoot,"100 mins");
lv_obj_set_style_text_font(ui_lbBoot, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btBack = lv_btn_create(ui_pnConfig);
lv_obj_set_width( ui_btBack, 100);
lv_obj_set_height( ui_btBack, 50);
lv_obj_set_x( ui_btBack, -50 );
lv_obj_set_y( ui_btBack, 119 );
lv_obj_set_align( ui_btBack, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lbConstbtBack = lv_label_create(ui_btBack);
lv_obj_set_width( ui_lbConstbtBack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbConstbtBack, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lbConstbtBack, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbConstbtBack,"Back");
lv_obj_set_style_text_font(ui_lbConstbtBack, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btReset = lv_btn_create(ui_pnConfig);
lv_obj_set_width( ui_btReset, 100);
lv_obj_set_height( ui_btReset, 50);
lv_obj_set_x( ui_btReset, 55 );
lv_obj_set_y( ui_btReset, 118 );
lv_obj_set_align( ui_btReset, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btReset, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lbConstbtReset = lv_label_create(ui_btReset);
lv_obj_set_width( ui_lbConstbtReset, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbConstbtReset, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lbConstbtReset, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbConstbtReset,"Restart");
lv_obj_set_style_text_font(ui_lbConstbtReset, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_arcRam = lv_arc_create(ui_pnConfig);
lv_obj_set_width( ui_arcRam, 80);
lv_obj_set_height( ui_arcRam, 80);
lv_obj_set_x( ui_arcRam, -55 );
lv_obj_set_y( ui_arcRam, 48 );
lv_obj_set_align( ui_arcRam, LV_ALIGN_CENTER );

lv_obj_set_style_arc_color(ui_arcRam, lv_color_hex(0xA30000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_arcRam, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_arcRam, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_arcRam, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_lbRamValue = lv_label_create(ui_arcRam);
lv_obj_set_width( ui_lbRamValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbRamValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lbRamValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbRamValue,"00");
lv_obj_set_style_text_font(ui_lbRamValue, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbConstRam = lv_label_create(ui_arcRam);
lv_obj_set_width( ui_lbConstRam, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbConstRam, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbConstRam, 0 );
lv_obj_set_y( ui_lbConstRam, 25 );
lv_obj_set_align( ui_lbConstRam, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbConstRam,"Ram");
lv_obj_set_style_text_font(ui_lbConstRam, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_arcFS = lv_arc_create(ui_pnConfig);
lv_obj_set_width( ui_arcFS, 80);
lv_obj_set_height( ui_arcFS, 80);
lv_obj_set_x( ui_arcFS, 55 );
lv_obj_set_y( ui_arcFS, 48 );
lv_obj_set_align( ui_arcFS, LV_ALIGN_CENTER );

lv_obj_set_style_arc_color(ui_arcFS, lv_color_hex(0x488201), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_arcFS, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_arcFS, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_arcFS, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_lbFSValue = lv_label_create(ui_arcFS);
lv_obj_set_width( ui_lbFSValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbFSValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lbFSValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbFSValue,"00");
lv_obj_set_style_text_font(ui_lbFSValue, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbConstFS = lv_label_create(ui_arcFS);
lv_obj_set_width( ui_lbConstFS, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbConstFS, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbConstFS, 0 );
lv_obj_set_y( ui_lbConstFS, 25 );
lv_obj_set_align( ui_lbConstFS, LV_ALIGN_CENTER );
lv_label_set_text(ui_lbConstFS,"FS");
lv_obj_set_style_text_font(ui_lbConstFS, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_btConfig, ui_event_btConfig, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btLock, ui_event_btLock, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btBack, ui_event_btBack, LV_EVENT_ALL, NULL);

}
